// Catálogo de objetivos de formação; não representa vagas abertas em um edital.
const specialtyNames = ['Ainda não decidi','Anestesiologia','Cardiologia','Cirurgia Cardiovascular','Cirurgia Geral','Cirurgia Pediátrica','Cirurgia Plástica','Cirurgia Torácica','Cirurgia Vascular','Clínica Médica','Coloproctologia','Dermatologia','Endocrinologia e Metabologia','Gastroenterologia','Genética Médica','Geriatria','Ginecologia e Obstetrícia','Hematologia e Hemoterapia','Infectologia','Medicina de Emergência','Medicina de Família e Comunidade','Medicina do Trabalho','Medicina Esportiva','Medicina Física e Reabilitação','Medicina Intensiva','Medicina Legal e Perícia Médica','Medicina Nuclear','Medicina Preventiva e Social','Nefrologia','Neurocirurgia','Neurologia','Oftalmologia','Oncologia Clínica','Ortopedia e Traumatologia','Otorrinolaringologia','Patologia','Patologia Clínica / Medicina Laboratorial','Pediatria','Pneumologia','Psiquiatria','Radiologia e Diagnóstico por Imagem','Radioterapia','Reumatologia','Urologia'];
const normalizeSpecialty = value => value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
let specialtyActive = -1;
function specialtyClose(){const input=document.querySelector('[name=specialty]'),list=document.querySelector('#specialty-options');if(!input||!list)return;list.hidden=true;input.setAttribute('aria-expanded','false');input.removeAttribute('aria-activedescendant');specialtyActive=-1;}
function specialtySearch(input,all=false){const list=document.querySelector('#specialty-options');if(!list)return;const query=all?'':normalizeSpecialty(input.value);const matches=specialtyNames.filter(name=>normalizeSpecialty(name).includes(query));list.innerHTML=matches.length?matches.map(name=>`<span role="option" aria-selected="false" id="specialty-${specialtyNames.indexOf(name)}" data-specialty="${name}">${name}</span>`).join(''):'<span class="specialty-empty" role="status">Nenhuma especialidade encontrada. Tente outro nome ou mantenha seu objetivo digitado.</span>';list.hidden=false;input.setAttribute('aria-expanded','true');input.removeAttribute('aria-activedescendant');specialtyActive=-1;}
function specialtyChoose(option){const input=document.querySelector('[name=specialty]');input.value=option.dataset.specialty;specialtyClose();input.focus();}
document.addEventListener('focusin',event=>{if(event.target.matches('[name=specialty]'))specialtySearch(event.target,specialtyNames.includes(event.target.value));});
document.addEventListener('input',event=>{if(event.target.matches('[name=specialty]'))specialtySearch(event.target);});
document.addEventListener('pointerdown',event=>{const option=event.target.closest('[data-specialty]');if(option){event.preventDefault();specialtyChoose(option);}else if(!event.target.closest('label:has([name=specialty])'))specialtyClose();});
document.addEventListener('focusout',event=>{if(event.target.matches('[name=specialty]'))specialtyClose();});
document.addEventListener('keydown',event=>{const input=event.target;if(!input.matches('[name=specialty]'))return;const list=document.querySelector('#specialty-options');if(event.key==='Escape'){event.preventDefault();specialtyClose();return}if(event.key==='ArrowDown'||event.key==='ArrowUp'){event.preventDefault();if(list.hidden)specialtySearch(input,true);const options=[...list.querySelectorAll('[role=option]')];if(!options.length)return;specialtyActive=(specialtyActive+(event.key==='ArrowDown'?1:-1)+options.length)%options.length;options.forEach((option,i)=>option.setAttribute('aria-selected',String(i===specialtyActive)));input.setAttribute('aria-activedescendant',options[specialtyActive].id);options[specialtyActive].scrollIntoView({block:'nearest'});}else if(event.key==='Enter'&&!list.hidden){const options=list.querySelectorAll('[role=option]');if(specialtyActive>=0||options.length===1){event.preventDefault();specialtyChoose(options[specialtyActive>=0?specialtyActive:0]);}}});
